#!/bin/sh
set -ef

: "${DPKG_ADMINDIR:=/var/lib/dpkg}"

find_fresh_ts() {
	{
		find "$@" -exec stat -c '%Y' '{}' '+' 2>/dev/null || :
		## duck and cover!
		echo 1
	} | sort -rn | head -n 1
}

_apt_update() {
	## update package lists; may fail sometimes,
	## e.g. soon-to-release channels like Debian "bullseye" @ 22.04.2021

	if [ $# = 0 ] ; then
		## (wannabe) smart package list update
		ts_sources=$(find_fresh_ts /etc/apt/ -follow -regextype egrep -regex '^/etc/apt/sources\.list(|\.d/[^/]+\.(list|sources))$' -type f)
		ts_lists=$(find_fresh_ts /var/lib/apt/lists/ -maxdepth 1 -regextype egrep -regex '^.+_Packages(|\.(bz2|gz|lz[4o]|xz|zstd?))$' -type f)
		if [ ${ts_sources} -gt ${ts_lists} ] ; then
			apt-env apt-get -y update
		fi
	else
		apt-env apt-get "$@" update
	fi
}

_dpkg_avail_hack() {
	set +e
	suite=$(sh -ec '. /etc/os-release ; printf "%s" "${VERSION_CODENAME}"' || : )
	## if ${suite} is empty then we're on Debian sid or so :)
	: "${suite:-sid}"
	set -e
	f="${DPKG_ADMINDIR}/available"
	case "${suite}" in
	stretch | buster | bionic | focal )
		## ref: https://unix.stackexchange.com/a/271387/49297
		if [ -s "$f" ] ; then
			return
		fi
		echo '# fixing "dpkg/available"' >&2
		/usr/lib/dpkg/methods/apt/update "${DPKG_ADMINDIR}" apt apt
	;;
	* )
		touch "$f"
	;;
	esac
}

_apt_update "$@"
_dpkg_avail_hack
