#!/bin/sh
set -ef

me="${0##*/}"
usage() {
	cat >&2 <<-EOF
	# usage: ${me} <binary>[:<package>] [...]
	EOF
	exit "${1:-0}"
}
[ $# != 0 ] || usage
[ -n "$1" ] || usage 1

_missing_bin=
_missing_pkg=
for i ; do
	unset bin pkg
	IFS=: read -r bin pkg <<-EOF
	$i
	EOF

	if [ -z "${bin}" ] ; then
		env printf "%q: 'binary' expected but empty: %q\\n" "${me}" "$i" >&2
		usage 1
	fi
	[ -n "${pkg}" ] || pkg=${bin}

	if command -v "${bin}" >/dev/null 2>&1 ; then
		continue
	fi

	_missing_bin="${_missing_bin}${_missing_bin:+ }${bin}"
	_missing_pkg="${_missing_pkg}${_missing_pkg:+ }${pkg}"
done

if [ -z "${_missing_bin}" ] ; then
	exit 0
fi

cat >&2 <<-EOF
# ${0##*/}: unable to find binaries:
#     ${_missing_bin}
# install packages:
#     apt-install ${_missing_pkg}
EOF
exit 1
