#!/bin/sh
set +e ; set -f

unset gitdir
x=$(ro-git rev-parse --path-format=absolute 2>/dev/null) || exit
if [ -n "$x" ] ; then
	## older git version which does not support "--path-format=absolute"
	gitdir=$(ro-git rev-parse --git-dir) || exit
else
	gitdir=$(ro-git rev-parse --path-format=absolute --git-dir) || exit
fi

unset topdir
case "${gitdir}" in
*/* ) topdir=${gitdir%/*} ; gitdir=${gitdir##*/} ;;
esac

[ -z "${topdir}" ] || cd "${topdir}/"

{
	for x in logs/refs objects/info objects/pack ; do
		x="${gitdir}/$x"
		[ -d "$x" ] || continue
		du -xhd1 "$x"
	done
	du -xhd1 "${gitdir}"
} | grep -Ev '^([0-9]+\.[0-9]+|[0-9]|1[0-9])K\s' | sort -Vk2
