#!/bin/sh
set +e ; set -f

if [ $# != 0 ] ; then
	case "$1" in
	-h | --help ) krd-du "$1" ;;
	-[bgkm] ) ;;
	--block-size ) ;;
	--block-size=* ) ;;
	-* ) usage 1 ;;
	esac
fi

unset gitdir
x=$(ro-git rev-parse --path-format=absolute 2>/dev/null) || exit
if [ -n "$x" ] ; then
	## older git version which does not support "--path-format=absolute"
	gitdir=$(ro-git rev-parse --git-dir) || exit
else
	gitdir=$(ro-git rev-parse --path-format=absolute --git-dir) || exit
fi

unset topdir
case "${gitdir}" in
*/* ) topdir=${gitdir%/*} ; gitdir=${gitdir##*/} ;;
esac

[ -z "${topdir}" ] || cd "${topdir}/"

krd-du "$@" "${gitdir}/logs/refs" "${gitdir}/objects/info" "${gitdir}/objects/pack" "${gitdir}"
