#!/bin/sh
set +e ; set -f

[ -n "${1:?}" ]

command -v deb-src-export >/dev/null 2>&1 || exit $?

case "$1" in
*/* ) dstdir="$1/src" ;;
* )   dstdir="/tmp/$1/src" ;;
esac
rm -rf "${dstdir}"
exec deb-src-export "${dstdir}"
