#!/bin/sh
set +e ; set -f

me="${0##*/}"
usage() {
	cat >&2 <<-EOF
	# usage: ${me} <package top directory> {<arch>|<host-arch>:<build-arch>} [env|arguments]
	EOF
	exit "${1:-0}"
}
[ $# != 0 ] || usage

check-bin-pkg sbuild xz:xz-utils || exit $?

_tmpdir() {
	TMPDIR="$1"
	TMP="$1"
	TEMPDIR="$1"
	TEMP="$1"
	export TMPDIR TMP TEMPDIR TEMP
}
## TODO: questionable
_tmpdir /tmp

[ -n "${1:?}" ]
[ -n "${2:?}" ]

case "$1" in
*/* ) topdir="$1" ;;
* )   topdir="/tmp/$1" ;;
esac
[ -d "${topdir}" ] || return 1

srcdir="${topdir}/src"
[ -d "${srcdir}" ] || return 2

_sbuild_args=
_append_args() {
	for __i ; do
		_sbuild_args="${_sbuild_args}${_sbuild_args:+ }$(env printf '%q' "${__i}" )"
	done ; unset __i
}
_prepend_args() {
	for __i ; do
		_sbuild_args="$(env printf '%q' "${__i}" )${_sbuild_args:+ }${_sbuild_args}"
	done ; unset __i
}

unset arch host_arch build_arch
case "$2" in
*:* )
	unset _xtra
	IFS=: read -r host_arch build_arch _xtra <<-EOF
	$i
	EOF

	if [ -z "${host_arch}" ] ; then
		env printf "%q: error: 'host-arch' expected but empty\\n" "${me}" >&2
		exit 1
	fi
	if [ -z "${build_arch}" ] ; then
		env printf "%q: error: 'build-arch' expected but empty\\n" "${me}" >&2
		exit 1
	fi
	if [ -n "${_xtra}" ] ; then
		env printf "%q: warning: extra data in 'host-arch:build-arch' specifier: %q\\n" "${me}" "${_xtra}" >&2
	fi
	unset _xtra
;;
* )
	host_arch="$2"
	build_arch="$2"
;;
esac

## done with args
shift 2

## manual handling of several options
arch_all=1
arch_any=1
enable_network=

for i ; do
	## naive splitting args and env
	case "$i" in

	## FAIL immediately when these options arrive
	--arch | --arch=* | --build | --build=* | --host | --host=* )
		env printf "%q: error: option is already handled: %q\\n" "${me}" "$i" >&2
		exit 1
	;;

	-A | --arch-all ) arch_all=1 ;;
	--no-arch-all ) arch_all= ;;

	--arch-any ) arch_any=1 ;;
	--no-arch-any ) arch_any= ;;

	--enable-network) enable_network=1 ;;
	--no-enable-network ) enable_network= ;;

	## implies "--no-arch-all"
	--append-to-version | --append-to-version=* | --make-binNMU | --make-binNMU=* )
		_append_args "$i"
		arch_all=
	;;

	-*  ) _append_args "$i" ;;
	=*  ) _append_args "$i" ;;
	*=  ) unset "$i" ;;
	*=* ) export "$i" ;;
	*   ) _append_args "$i" ;;
	esac
done ; unset i

## prepend args (so option order is opposite to "native")

if [ -n "${enable_network}" ] ; then
	_prepend_args --enable-network
fi

if [ -n "${arch_all}" ] ; then
	_prepend_args --arch-all
else
	_prepend_args --no-arch-all
fi

if [ -n "${arch_any}" ] ; then
	_prepend_args --arch-any
else
	_prepend_args --no-arch-any
fi

## TODO: verify later all this mess
arch="${host_arch}"
if [ "${host_arch}" = "${build_arch}" ] ; then
	_prepend_args "--arch=${arch}"
else
	_prepend_args "--build=${build_arch}"
	_prepend_args "--host=${host_arch}"
fi

builddir="${topdir}/${arch}"
mkdir -p "${topdir}/all" "${builddir}" "${builddir}-all" "${builddir}-debug"

cd "${builddir}"

set +f
for i in "${srcdir}"/*.dsc ; do
	## I'm NOT proud of using "eval" here :(
	eval "idle sbuild ${_sbuild_args} $i" || exit $?
	find -name '*.build' -type l -exec rm -f {} +
	find -name '*.build' -type f -exec xz -9vv {} +
done

find \
  -regextype egrep -regex '.+all\.d?deb$' -type f \
  -exec mv -fvt "../${arch}-all" {} +

find \
  -name '*.ddeb' -type f \
  -exec mv -fvt "../${arch}-debug" {} +
find \
  -regextype egrep -regex '.+dbgsym_[^_]+_'"${arch}"'\.d?deb$' -type f \
  -exec mv -fvt "../${arch}-debug" {} +

cd "${builddir}-all"
find -type f -exec mv -nvt '../all' {} +

exit 0
