#!/bin/sh
set +e ; set -f

[ -n "${1:?}" ]

check-bin-pkg deb-src-export || exit $?

case "$1" in
*/* ) dstdir="$1/src" ;;
* )   dstdir="/tmp/$1/src" ;;
esac
rm -rf "${dstdir}"
exec deb-src-export "${dstdir}"
