#!/bin/sh
set -ef

have_cmd() { command -v "$1" </dev/null >/dev/null 2>&1 ; }

if have_cmd mawk ; then
	exec mawk "$@"
fi
if have_cmd awk ; then
	exec awk "$@"
fi
## really last effort
exec gawk "$@"
